/**
 * The names of the tokens returned by the Argdown lexer.
 * These can be used to register [[IArgdownPlugin.tokenListeners]].
 */
export enum TokenNames {
  INCOMING_SUPPORT = "IncomingSupport",
  INCOMING_ATTACK = "IncomingAttack",
  INCOMING_UNDERCUT = "IncomingUndercut",
  CONTRADICTION = "Contradiction",
  IMPLIES = "Implies",
  REVERSE_IMPLIES = "ReverseImplies",
  PRESUPPOSED_BY = "PresupposedBy",
  REVERSE_PRESUPPOSED_BY = "ReversePresupposedBy",
  SPECIFIES = "Specifies",
  REVERSE_SPECIFIES = "ReverseSpecifies",
  EXAMPLE_FOR = "ExampleFor",
  REVERSE_EXAMPLE_FOR = "ReverseExampleFor",
  QUESTIONS = "QuestionsRelation",
  REVERSE_QUESTIONS = "ReverseQuestions",
  ANSWERS = "AnswersRelation",
  REVERSE_ANSWERS = "ReverseAnswers",
  CITED_BY = "CitedBy",
  REVERSE_CITED_BY = "ReverseCitedBy",
  EQUAL = "EqualRelation",
  POTENTIALLY_EQUAL = "PotentiallyEqualRelation",
  OUTGOING_SUPPORT = "OutgoingSupport",
  OUTGOING_ATTACK = "OutgoingAttack",
  OUTGOING_UNDERCUT = "OutgoingUndercut",
  FREESTYLE = "Freestyle",
  UNUSED_CONTROL_CHAR = "UnusedControlChar",
  EMPTYLINE = "Emptyline",
  NEWLINE = "Newline",
  INFERENCE_START = "InferenceStart",
  INFERENCE_END = "InferenceEnd",
  STATEMENT_DEFINITION = "StatementDefinition",
  STATEMENT_REFERENCE = "StatementReference",
  BLOCK_START = "BlockStart",
  BLOCK_CONTENT = "BlockContent",
  STATEMENT_MENTION = "StatementMention",
  ARGUMENT_DEFINITION = "ArgumentDefinition",
  ARGUMENT_REFERENCE = "ArgumentReference",
  ARGUMENT_MENTION = "ArgumentMention",
  INDENT = "Indent",
  DEDENT = "Dedent",
  FRONT_MATTER = "FrontMatter",
  DATA = "Data",
  ORDERED_LIST_ITEM = "OrderedListItem",
  UNORDERED_LIST_ITEM = "UnorderedListItem",
  HEADING_START = "HeadingStart",
  LIST_DELIMITER = "ListDelimiter",
  STATEMENT_NUMBER = "StatementNumber",
  ASTERISK_BOLD_START = "AsteriskBoldStart",
  ASTERISK_BOLD_END = "AsteriskBoldEnd",
  ASTERISK_ITALIC_START = "AsteriskItalicStart",
  ASTERISK_ITALIC_END = "AsteriskItalicEnd",
  UNDERSCORE_BOLD_START = "UnderscoreBoldStart",
  UNDERSCORE_BOLD_END = "UnderscoreBoldEnd",
  UNDERSCORE_ITALIC_START = "UnderscoreItalicStart",
  UNDERSCORE_ITALIC_END = "UnderscoreItalicEnd",
  COMMENT = "Comment",
  TAG = "Tag",
  LINK = "Link",
  ESCAPED_CHAR = "EscapedChar",
  SPECIAL_CHAR = "SpecialChar",
  SPACES = "Spaces",
  EOF = "EOF"
}
